# Generated by Django 4.2.4 on 2023-08-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boxer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.person')),
                ('weight_category', models.CharField(choices=[('feather', 'Feather'), ('light', 'Light'), ('middle', 'Middle'), ('heavy light', 'Heavy Light'), ('super heavy', 'Super Heavy')], default='middle', max_length=30)),
                ('fights_total', models.IntegerField()),
                ('fights_won', models.IntegerField()),
            ],
            bases=('members.person',),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.person')),
                ('role', models.CharField(max_length=25)),
            ],
            bases=('members.person',),
        ),
    ]
